url: "https://allthemore247.github.io/testwebsite/" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "AlltheMore's Testing Site" # the name of your site, e.g. ACME Corp.
highlighter: "rouge"
plugins: ""