url: "https://allthemore247.github.io/testwebsite" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
permalink: /posts/:title # used to set the url of each post to a title instead of a date
title: "AlltheMore's Testing Site" # the name of your site, e.g. ACME Corp.
highlighter: "rouge"